app:
  db:
    host: localhost
    port: 5432
    name: testBank
    username: postgres
    password: 1234

spring:
  application:
    name: testBank
  datasource:
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.name}?ApplicationName=${spring.application.name}
    username: ${app.db.username}
    password: ${app.db.password}

spring.liquibase.change-log: classpath:liquibase/changelog-master.yml